spring:
  application:
    name: client-app  # Identify this application
  freemarker:
    enabled: false
  thymeleaf:
    cache: false
    prefix: classpath:/client-app/templates/


# HTTP Server
server.port: 1111   # HTTP (Tomcat) port

# Discovery Server Access\
eureka:
  client:
    serviceUrl:
      defaultZone: http://${service.finder.hostname}:1010/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
